version: '3'

services:
  blip-cards:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "8081:8081"
    command: npm start
